### ISSUE TITLE
Testing on devices

### ISSUE THREAD

**Issue by Merri** [Merri/react-tap-or-click#4]
There are three things to test on touch devices:
1. Can page be scrolled from the element and not get a click when releasing touch?
2. When clicked element disappears there should be no another click on background element at the same position.
3. There should be no duplicate clicks (for example first by touchend event and then by click event).

The first two cases can be tested in [this pen](http://codepen.io/Merri/full/LGRxrq). The third case probably happens very obviously in regular usage (read: I hit my lazy mode and just want to play some Medieval: Total War now).
### Phones
- Chrome iPhone 5 iOS 9
- Safari iPhone 5 iOS 9
- Chrome Android 5 Lollipop
- Firefox Android 5 Lollipop
- IE11 Windows Phone 8.1
### Emulators
- Android Browser 4.1, 4.3, 4.4, 5.1
### Desktop browsers
- Chrome
- Firefox
- Edge
- IE11

Desktop browsers tested also in mobile/responsive mode if feature available.
## Should be tested
- Validate Android Browser 4.1, 4.3, 4.4 on a real device
- Chrome and Firefox on Android 4.1, 4.3, 4.4
- Other devices that are "popular enough" to be considered to be supported

**Comment by nuschk** [comment]
Works with the default browsers on the following Android versions (on Emulator)
- [x] 4.1(Jelly Bean)
- [x] 4.3 (Jelly Bean)
- [x] 4.4 (Kitkat)
- [x] 5.1 (Lollipop)

I couldn't test with chrome and firefox though (I don't know how to install them in the emulator and the process seems rather complicated). I think, however, that firefox and chrome are the same versions across all android devices anyway, so testing on the latest version should be ok for older ones, too.

I will be adding the latest snapshot into our responsive webapp and our webviews for the ios app and see if it works.

**Comment by Merri** [comment]
Great to know!

I tested now with a real Windows 8.1 Phone (Lumia 520) and is working. So overall the basic features seem to be ok and the remaining bugs are cases that become visible only by usage in real environments.
